package utils.networks;

public enum PermissionConfig {
	PERMISSION_ADMIN_ACTIVE,
	PERMISSION_ADMIN_INACTIVE, 
	PERMISSION_ADMIN_LOCK, 
	PERMISSION_CAPTIEN, 
	PERMISSION_MAIL,
	PERMISSION_LOG_CHUYENTIEN,
	PERMISSION_LOG_NHANTIEN, 
	PERMISSION_BAN_GIFTCODE, 
	PERMISSION_GIFTCODE_CHUASUDUNG,
	PERMISSION_GIFTCODE_DASUDUNG

}
